using UnityEngine;
using System.Collections;

public static class ShockPhrases {
	public static string[] phrases = new string[]{
		"Alack!",
		"Alas!",
		"Ahhh!",
		"Applesauce!",
		"Argh!",
		"Bah humbug!",
		"Balderdash!",
		"Baloney!",
		"Barf!",
		"Beard of Zeus!",
		"Blarg!",
		"Blimey!",
		"Bull feathers!",
		"Bully!",
		//"Cat's pajamas!",
		"Codswallop!",
		//"Cowabunga!",
		"Criminy!",
		"Cripes!",
		"Dear me!",
		"Dingbats!",
		"Eeek!",
		"Egads!",
		"Fiddlesticks!",
		"Fie!",
		"Gadzooks!",
		"Gasp!",
		"Golly!",
		"Golly gee!",
		"Good heavens!",
		"Great Scott!",
		"Hello?",
		"Help!",
		"Holy mackerel!",
		"Holy smoke!",
		"Is that you?",
		"Is someone there?",
		"Jeepers!",
		//"Jiminy crickets!",
		"Jinkies!",
		//"Just the wind, I guess...",
		"Leaping lizards!",
		"Malarkey!",
		"My stars and garters!",
		"No more!",
		"Nuts!",
		"Odin's raven!",
		"Oh my!",
		"Oh no!",
		"Save me!",
		"Somebody help!",
		"Tarnations!",
		//"The end is nigh!",
		"Thor's hammer!",
		"What?",
		"What was that?",
		"Who's there?",
		"Woe is me!",
		"Yikes!",
		"Yow!",
		"Yowzers!",
		"Zounds!",
	};

	public static string Phrase(int dam){
		int index = UnityEngine.Random.Range (0,phrases.Length-1);
		return phrases[index];//+"("+dam.ToString ()+")";
	}
}
